steps:
  - name: prettier
    image: node:24.12.0-alpine3.22
    commands:
      - apk add make
      - npm ci
      - make npm prettier-test

  - name: typecheck
    image: node:24.12.0-alpine3.22
    environment:
      SHA: ${CI_COMMIT_SHA:0:7}
    commands:
      - apk add make git
      - make sha
      - make typecheck
    depends_on:
      - prettier

  - name: lint
    image: golang:1.24.0-alpine3.21
    commands:
      - apk add make git curl jq gcc g++
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint/v2@v2.8.0
      - make lint

  - name: test
    image: golang:1.24.0-alpine3.21
    commands:
      - apk add make git exiftool ffmpeg gcc g++
      - make test
    depends_on:
      - prettier

  - name: build
    image: golang:1.24.0-bookworm
    commands:
      - apt-get update && apt-get install -y make build-essential git
      - make build
    depends_on:
      - prettier

  - name: build-assets
    image: node:24.12.0-alpine3.22
    commands:
      - apk add make
      - npm ci
      - make assets
    depends_on:
      - prettier

when:
  event:
    - push