steps:
  - name: prettier
    image: node:24.12.0-alpine3.22
    commands:
      - apk add make
      - npm ci
      - make npm prettier-test
      - make sha
      - make typecheck
      - make test-ui

  - name: lint
    image: golangci/golangci-lint:v2.8.0
    commands:
      - make lint

  - name: test
    image: golang:1.24.0-alpine3.21
    commands:
      - apk add make git exiftool ffmpeg gcc g++
      - make test
    depends_on:
      - prettier

  - name: build
    image: golang:1.24.0-bookworm
    commands:
      - apt-get update && apt-get install -y make build-essential git
      - make build
    depends_on:
      - prettier

  - name: build-assets
    image: node:24.12.0-alpine3.22
    commands:
      - apk add make
      - npm ci
      - make assets
    depends_on:
      - prettier

when:
  event:
    - push