steps:
  - name: prettier
    image: node:20.18.3-alpine3.21
    commands:
      - apk add make
      - npm i -g prettier@3.6.2
      - make npm prettier-test

  - name: lint
    image: golang:1.24.0-alpine3.21
    commands:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - apk add make git curl jq gcc g++
      - make lint

  - name: test
    image: golang:1.24.0-alpine3.21
    commands:
      - apk add make git exiftool ffmpeg gcc g++
      - make test
    depends_on:
      - prettier

  - name: build
    image: golang:1.24.0-bookworm
    commands:
      - apt-get update && apt-get install -y make build-essential git
      - make build
    depends_on:
      - prettier

  - name: build-assets
    image: node:20.18.3-alpine3.21
    commands:
      - apk add make
      - npm ci
      - make assets
    depends_on:
      - prettier

when:
  event:
    - push