steps:
  - name: prettier
    image: node:24.12.0-alpine3.22
    commands:
      - apk add make
      - npm ci
      - make npm prettier-test
      - make sha
      - make typecheck
      - make test-ui

  - name: lint
    image: golangci/golangci-lint:v2.8.0
    commands:
      - make lint

  - name: test
    image: golang:1.25.10-alpine3.23
    commands:
      - apk add make git exiftool ffmpeg gcc g++
      - make test
    depends_on:
      - prettier

  - name: build
    image: golang:1.25.10-alpine3.23
    commands:
      - apk add make build-base git
      - make build
    depends_on:
      - prettier

  - name: build-assets
    image: node:24.12.0-alpine3.22
    commands:
      - apk add make
      - npm ci
      - make assets
    depends_on:
      - prettier

  - name: build-push-rgallery
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: cmd/rgallery/Dockerfile
      platforms:
        - linux/arm64
        - linux/amd64
      repo: robbymilo/rgallery
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - ${CI_COMMIT_SHA}

  - name: build-push-rgallery-resize
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: cmd/rgallery-resize/Dockerfile
      platforms:
        - linux/arm64
        - linux/amd64
      repo: robbymilo/rgallery
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - resize-${CI_COMMIT_SHA}

  - name: build-push-rgallery-geo
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: cmd/rgallery-geo/Dockerfile
      platforms:
        - linux/arm64
        - linux/amd64
      repo: robbymilo/rgallery
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - geo-${CI_COMMIT_SHA}

when:
  event:
    - push